// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web2Hotel.Models;

namespace Web2Hotel.Migrations
{
    [DbContext(typeof(Web2HotelContext))]
    partial class Web2HotelContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Web2Hotel.Models.Contacto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Estado")
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("varchar(45)");

                    b.HasKey("Id");

                    b.ToTable("Contacto");
                });

            modelBuilder.Entity("Web2Hotel.Models.Habitacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    b.Property<int>("Capacidad")
                        .HasColumnType("int(11)");

                    b.Property<int>("Numero")
                        .HasColumnType("int(11)");

                    b.HasKey("Id");

                    b.HasIndex("Numero")
                        .IsUnique()
                        .HasName("Numero_UNIQUE");

                    b.ToTable("Habitacion");
                });

            modelBuilder.Entity("Web2Hotel.Models.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<int>("CreationId")
                        .HasColumnType("int(11)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("varchar(45)");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime");

                    b.Property<int>("HabitacionId")
                        .HasColumnType("int(11)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int(11)");

                    b.HasKey("Id");

                    b.HasIndex("CreationId")
                        .HasName("Creator_idx");

                    b.HasIndex("HabitacionId")
                        .HasName("Habitacion_idx");

                    b.HasIndex("UsuarioId")
                        .HasName("User_idx");

                    b.ToTable("Reserva");
                });

            modelBuilder.Entity("Web2Hotel.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    b.Property<string>("Apelllido")
                        .IsRequired()
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Telefono")
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(45)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasName("Username_UNIQUE");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Web2Hotel.Models.Reserva", b =>
                {
                    b.HasOne("Web2Hotel.Models.Usuario", "Creation")
                        .WithMany("ReservaCreation")
                        .HasForeignKey("CreationId")
                        .HasConstraintName("Creator");

                    b.HasOne("Web2Hotel.Models.Habitacion", "Habitacion")
                        .WithMany("Reserva")
                        .HasForeignKey("HabitacionId")
                        .HasConstraintName("Habitacion");

                    b.HasOne("Web2Hotel.Models.Usuario", "Usuario")
                        .WithMany("ReservaUsuario")
                        .HasForeignKey("UsuarioId")
                        .HasConstraintName("User");
                });
#pragma warning restore 612, 618
        }
    }
}
